# Welcome to Jekyll!
title: Erika & Mark's Wedding
timezone: America/Los_Angeles
collections:
  uploads:
    title: Uploads
    output: true
email: web.art@adriandiaz.ca
description:  "Erika Diaz and Mark Fairey's Wedding | Save the date: May 6, 2017"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erika-mark.com" # the base hostname & protocol for your site
                              # http://localhost:4000
twitter_username: ONZOart
github_username:  adriandgr
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima

include: ["_pages"]
permalink: /:categories/:title/