# Welcome to Jekyll!
title: Erika & Mark's Wedding
email: web.art@adriandiaz.ca
description: > # this means to ignore newlines until "baseurl:"
  Save the date: May 6, 2017.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
                              # http://localhost:4000
twitter_username: jekyllrb
github_username:  jekyll
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima

include: ["_pages"]
permalink: /:categories/:title/